name: DirtyLeaderboards
description: $description
version: '${version}'

main: me.romix.dirtyLeaderboards.DirtyLeaderboards
api-version: '1.21.9'
load: POSTWORLD
folia-supported: false

author: romix_42
website: https://github.com/romix42/DirtyLeaderboards

softdepend:
  - Skript
  - PlaceholderAPI

commands:
  dirtyleaderboards:
    description: Manage DirtyLeaderboards displays
    aliases: [ dlb, dirtyleaderboard, leaderboards, dirtyboards, boards, db, dirtyboard, leaderboard, lb, dlbs ]
    permission: dirtyleaderboards.admin

permissions:
  dirtyleaderboards.admin:
    description: Access to all DirtyLeaderboards commands
    default: op
